version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dnd-tracker-client
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/data.db
    env_file:
      - .env
    ports:
      - '4001:3000'
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
