version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vsop-archive-client
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data.db
    env_file:
      - .env
    ports:
      - '4001:4001'
    volumes:
      - ./data.db:/app/data.db
    networks:
      - default
networks:
  default:
    name: nginx
    external: true

